### ISSUE TITLE
Rule with night ends gives error after latest update

### ISSUE THREAD

**Issue by pimagical** [pimatic/pimatic-sunrise#2]
Rule with "If night ends" gives error and won't work after latest update.

error [pimatic]: timediff > 0

https://github.com/pimatic/pimatic/issues/655

**Comment by pimagical** [comment]
Ok after a whole week testing i know it for sure. Every rule with use of night (included before night, after night, night start, night ends) is all failing! (sunset and solar noon are working)

**Comment by sweetpi** [comment]
Still after the last update?

**Comment by pimagical** [comment]
Yes i directly updated to the latest 0.8.1 yesterday. I cant find the update in GIT that caused this defect. I updated something (thought it was sunrise) on 17 May and it directly gave issues with a lot of rules. Im back on time values instead of night values in the rules.

**Comment by pimagical** [comment]
When making a rule with night and submit you will get a timediff error, the same via editing the config after a restart the rule will disappear in the gui rule page with an error.

**Comment by sweetpi** [comment]
ok thanks, I will take a closer look at this case.

**Comment by pimagical** [comment]
I experienced a 2 hour time delay in a rule. Because the system time was UTC (explained maybe the 2h difference) and has been changed to local time with use of:

> sudo dpkg-reconfigure tzdata

Current default time zone: 'Europe/Amsterdam'
Local time is now:      Wed May 27 00:45:00 CEST 2015.
Universal Time is now:  Tue May 26 22:45:00 UTC 2015.

I tested the sunrise rules again with the correct system time and this didn't solve the timediff issues.

**Comment by sweetpi** [comment]
@pimagical Could you try with v0.8.2?

**Comment by pimagical** [comment]
0.8.2 is not working. Edited the time based rule to a sunrise rule. When the rule is saved now a "Oops typeof p.changeListner is "function"" error message is being showed.

Rule: If its after night then set $status to "Good night, sleep well!"

**Comment by pimagical** [comment]
I fixed the problem with deleting the rule and adding a new rule with the exact same actions in it and it worked successfully again strangely. The problem never happened again.

So from my experience I would say a year ago a rule can be broken even if the rule actions are right.

**Comment by mwittig** [comment]
I think the problem is that the `night` and `nightEnd` events yield an invalid date for some combinations of date and location. This also effects the use of the predicates as part of rules. See also https://github.com/mourner/suncalc/issues/117

Thus I'll mark  these events as deprecated. My suggestion is to use `sunrise`and `sunset`  instead.
