### ISSUE TITLE
Ability to change locales

### ISSUE THREAD

**Issue by kenci** [pimatic/pimatic-sunrise#5]
It should be possible to set the locale in plugin settings or reuse the `locale` property from the main config file `config.json`. Because i have set the system locale to "en-us" and don't want to change the system locale to "de-de" because of pimatic-sunrise plugin to display "23:38" instead of "11:38 PM"

**Comment by mwittig** [comment]
The plugin uses the timezone set on system where pimatic is installed. So, iny your case it should display the time  properly if you the timezone on the system accordingly. See also https://forum.pimatic.org/topic/963/solved-wrong-time-zone-how-to-correct/4

Additionally, it is now possible to set another timezone on a SunriseDevice. See README for defatils
